package com.algartech.clima.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.algartech.clima.entity.Historico;
import com.algartech.clima.entity.User;
import com.algartech.clima.repository.HistoricoRepository;
import com.algartech.clima.repository.UserRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path="/historico") // This means URL's start with /demo (after Application path)
public class HistoricoController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private HistoricoRepository historicoRepository;
  
  

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewUser (@RequestParam String name
      , @RequestParam String email) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Historico n = new Historico();
    n.setCiudad(name);
  
    historicoRepository.save(n);
    return "Saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Historico> getAllHistorico() {
    // This returns a JSON or XML with the users
    return historicoRepository.findAll();
  }
}
